Add files via upload
Argentum11/CCC_LibrarySystem pull request #4
Opened 2022-11-12 07:54 UTC by hong-511

## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
**Describe what the change is**
You don't need to explain HOW you change the code, just shortly describe what's different

## Related Issue
If applicable, refernce to the issue related to this pull request.
type close#n to relate to the current issue, where n stands for the number of the issue

2022-11-12 10:30 UTC, Argentum11 requested changes
Please change the default PR title and Description to let us know what has been done

2022-11-12 17:05 UTC, Argentum11 approved these changes

2022-11-12 17:07 UTC, Argentum11 requested changes
@hong-511
I changed the description of this PR, please check if I missed anything

2022-11-13 05:24 UTC, hong-511 commented
> @hong-511 I changed the description of this PR, please check if I missed anything

OK.

2022-11-13 05:32 UTC, Argentum11 approved these changes

2022-11-13 05:32 UTC, merged